# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_remove_video_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
