# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_channel_channelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='author',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channelid',
            field=models.TextField(unique=True),
        ),
    ]
