# Generated by Django 2.2 on 2019-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_nullable_statistics_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='thumbnail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='uploads_playlist',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
