# Generated by Django 2.2 on 2019-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0016_video__title__index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(
                fields=['uploader', 'deleted', '-uploaded'],
                name='youtube_vid_uploade_bb5325_idx'),
        ),
    ]
